### ISSUE TITLE
Peptide Shaker Import Filters - Precursor Accuracy

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#114]
Hey folks,

is it possible that there is something going wrong with the Peptide Shaker "Precursor Accuracy" import filter?

###
Mon Jan 18 16:07:30 PST 2016        29638 of the best scoring peptides were excluded by the import filters:
Mon Jan 18 16:07:30 PST 2016            - 2.8% peptide mapping to both target and decoy.
Mon Jan 18 16:07:30 PST 2016            - 85.9% peptide length less than 7 or greater than 45,
Mon Jan 18 16:07:30 PST 2016                or number of missed cleavage sites outside of the range [0-2].
Mon Jan 18 16:07:30 PST 2016            - 11.3% unrecognized modifications.
Mon Jan 18 16:07:30 PST 2016        File import completed. 64296 first hits imported (191873 secondary) from 75229 spectra.
###
vs. with 20ppm filter
###
Mon Jan 18 16:48:38 PST 2016        **116474** of the best scoring peptides were excluded by the import filters:
Mon Jan 18 16:48:38 PST 2016            - 23.2% peptide length less than 7 or greater than 45,
Mon Jan 18 16:48:38 PST 2016                or number of missed cleavage sites outside of the range [0-2].
Mon Jan 18 16:48:38 PST 2016            - **71.1%** peptide mass deviation bigger than 20.0 ppm.
Mon Jan 18 16:48:38 PST 2016            - 5.5% unrecognized modifications.
###

Note: Comet searches were done with plus/minus 15ppm. Only 450 PSMs have an isotope error (so that can't be the cause), also only 219 PSMs are outside the 15ppm window (207 have an isotope error of -1, and the remaining 12 must have lost their variable Met-oxidation, but have to follow up on that).

Do you see something similar on your side?

**Comment by mvaudel** [comment]
Hi Ulrich,

There is definitely something going wrong with these numbers. I don't
recall having changed this code recently and it I just checked that it
works fine on my side using OMSSA and X!Tandem. Will do some more testing
using the latest version of Comet and come back to you.

Best regards,

Marc

2016-01-19 1:59 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
hmmm ... will take a 2nd look tomorrow. i had some issues that brought me
from 6000 PSMs to roughly 1000, and the only difference i could spot was
this filter that i thought shouldn't make a difference. let me know if it
is the same on your side, otherwise i will try to reproduce it tmw. cheers,
u

**Comment by hbarsnes** [comment]
Again, this is most likely connected to this issue: https://github.com/compomics/peptide-shaker/issues/116, where a PTM gets lost and the remaining mass deviation becomes incorrect.

**Comment by hbarsnes** [comment]
The issue should have been fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
fear it still doesn't work properly and we have to open the issue again ... here some new data from PeptideShaker 1.5.1-beta; rResults are from X! Tandem in this case (searched with plus/minus 15 ppm):

without the precursor filter I get a total of 6042 PSMs with 5920 within plus/minus 10ppm. but when I apply the precursor filter, I go down to 849 PSMs (but which at least are all really between -10 and plus 10 ppm).

can't really pinpoint the problem. but here some more observations when applying the filter:
(i) my relative amounts of TMT@Nter and acetyl@Nter goes down, pyrrolidones go all up.
(ii) before roughly 72% of my PSMs have an internal TMT-labeled lysine (Note: it is a TAILS sample thus this is expected), after applying the filter this goes down to 33%. the relative amount of cmCys in the contrary goes up (from 20 to 32%).
(iii) my average peptide length goes down, from something around 23 aa to 15 aa.
(iv) No PSMs with an isotope error survive. Which makes some sense maybe, but not to that extent i fear. Before there are 5633 PSMs with an isotope error "0", and 400 with ">0", so it shouldn't go down to 850, right?

hope it helps a bit to figure out what is going on.

**Comment by mvaudel** [comment]
Hi Ulrich,

Can you check whether the new releases solve this issue on your side? The numbers make sense as far as we tested!

Best regards,

Marc

**Comment by ulriche** [comment]
hmmm ....

maybe I misunderstand what the Import filter is supposed to do ... but on my side it just still doesn't do the right thing, or not the thing I expect it to do ...

so I searched my data in comet with plus/minus 15 ppm precursor accuracy. after import into PeptideShaker (without a precursor filter), out of my 15k PSMs 97% are within plus/minus 10ppm.

but when I import with a 10ppm import filter, I go down to 167 PSMs - but these ones are at least within 10ppm. Interestingly all these 167 have an isotope error of "-1" - so I think the problem is somehow linked with the isotope error.

but on the other hand, of my initial 15k PSMs only 2.3% were "-1", and more than 95% had an isotope error of "0". so somehow there must be more to it.

**Comment by ulriche** [comment]
just as a quick follow up:

The ppm-import filter is still not working for me (PS 1.7.2). Data were originally searched with plus/minus 15ppm (comet) and gave an ID rate of >30% (without ppm import filter). But as soon as I use the import filter, I go down to 0.8% (15ppm) and 0.5% (10ppm).

do you see the same on your side? it shouldn't be linked with me variable N-terminal modifications as it is a PreTAILS dataset (approx. 8% N-termini). what I do see, and I guess I should have noticed that earlier is the following:

**Good Import:**
Fri Feb 05 16:36:31 PST 2016        **4599** identified spectra (10.2%) did not present a valid peptide.
Fri Feb 05 16:36:31 PST 2016        **12197** of the best scoring peptides were excluded by the import filters:
Fri Feb 05 16:36:31 PST 2016            - 2.3% peptide not matching to the database.
Fri Feb 05 16:36:31 PST 2016            - 3.4% peptide mapping to both target and decoy.
Fri Feb 05 16:36:31 PST 2016            - 83.6% peptide length less than 7 or greater than 45,
Fri Feb 05 16:36:31 PST 2016                or number of missed cleavage sites outside of the range [0-2].
Fri Feb 05 16:36:31 PST 2016            - 10.7% unrecognized modifications.

**Bad Import:**
Fri Feb 05 16:28:34 PST 2016        **37176** identified spectra (82.8%) did not present a valid peptide.
Fri Feb 05 16:28:34 PST 2016        **106681** of the best scoring peptides were excluded by the import filters:
Fri Feb 05 16:28:34 PST 2016            - 10.9% peptide length less than 7 or greater than 45,
Fri Feb 05 16:28:34 PST 2016                or number of missed cleavage sites outside of the range [0-2].
Fri Feb 05 16:28:34 PST 2016            - 85.5% peptide presenting high mass or isotopic deviation.
Fri Feb 05 16:28:34 PST 2016            - 3.5% unrecognized modifications.

Meaning that my PSMs are (i) not recognized as valid peptide anymore (37k vs. 4.6k), and (ii) are excluded because of the import filter (105k vs 12k).

Maybe it helps.
u

**Comment by hbarsnes** [comment]
Should be fixed with the release of PeptideShaker 1.7.3. Or at least much improved. There was a bug in the mass deviation filter where the minimum allowed isotope number was used for both the min and max values when calculating the mass deviation.

**Comment by ulriche** [comment]
cool ... thanks ...

**Comment by ulriche** [comment]
just finished testing the import filter in PS 1.7.3 - looking great!!!
THANKS!!!
