### ISSUE TITLE
PS - Theoretical Mass Column: something is going wrong here

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/peptide-shaker#126]
not sure what it is, but something must have severely changed here ...

e.g. peptide SLLLSVNAR
- according to PeptideShaker: Theoretical Mass of 1019.56
- according to Expasy Peptide Mass: 971.5764

or peptide LLSGFGLER
- according to PeptideShaker: Theoretical Mass of 1038.53
- according to Expasy Peptide Mass: 990.5498

in my case more than 70% of all PSMs are affected, but interestingly 30% are perfectly fine and I don't really see a pattern:
e.g. peptide TISEIYQPR
- according to PeptideShaker: Theoretical Mass of 1105.57
- according to Expasy Peptide Mass: 1105.57

no idea what it is ... but the mass deltas are close to "nice" numbers ... e.g. 64, 49, 48, 46, 33, 32, 31, 30, 29, 17, 16, 15, 14, 13, 1, 0, -1, -2, -3 ... so something like xx.99 or xx.98, but not further away.

any ideas?

**Comment by hbarsnes** [comment]
And you're sure that none of the peptides where this occurs are modified I assume? Neither with variable of fixed modifications?

And is it just a coincidence that both of your examples have a mass difference of 47.98? Can't think of a natural explanation for this distance, but mathematically it matches a triple oxidation (47.98 / 3 = 15.99). Cannot say that this makes any sense though.

But I guess I'm trying to read too much into your two examples. Which search engine are these results from? And could you send us the zipped cpsx export?

BTW, from where in PeptideShaker are you finding the above theoretical masses? In the exports?

**Comment by ulriche** [comment]
yep, in the PSM exports, and noteworthy in all of them ...

so independent if I search with Comet, MSGF+, X!Tandem, or MS Amanda.

had sorted the peptides by maximum delta mass, thus the 48 ones at the
beginning. will dig out one cpsx export quickly and will send off list.

haven't seen that behavior with the other releases though.
thanks already
u

**Comment by hbarsnes** [comment]
In that case I think the exported file itself should be enough (at least as a start). But I will do some test tomorrow to see if the issue is reproducible on our side as well.

**Comment by ulriche** [comment]
will send the excel file too - off list again! ;-)

**Comment by ulriche** [comment]
one more observation ...

in MSGF+: when I search via ArgC, GluC, or LysR - I am getting the rror, when searching "unspecific", all my results are suddenly within the specified ppm range. no idea if that makes any sense to you.

**Comment by ulriche** [comment]
did another round of analysis - now for GluC they all look good.

maybe it is a LysR problem only or mainly.

**Comment by hbarsnes** [comment]
We were able to reproduce the issue on our side and have come up with a fix that seems to work. The problem was in the calculation of the theoretical mass combined with the use of multiple threads running at the same time. This resulted in the error sometimes occurring and sometimes not, even on the same dataset. We'll release a new version as soon as possible, hopefully this evening.

**Comment by hbarsnes** [comment]
Should be fixed in PeptideShaker v1.7.0. You will have to reprocess your data though, i.e. it's not enough to reopen the saved PeptideShaker project.

**Comment by ulriche** [comment]
looks great so far! big thanks!

**Comment by ulriche** [comment]
hmmm ... fear the error is back. not sure why but in my latest results 50% of my results have a ppm errors of more than "-20ppm" - interestingly it is only that direction (so no crazy ppm errors in the "plus" direction")

**Comment by hbarsnes** [comment]
We didn't change anything related to this in the recent versions as far as I can remember. Which search engines are you using? And can you see any pattern in the peptides with the large errors?

**Comment by ulriche** [comment]
no clear pattern - the file I am looking at right now is coming from comet.

like last time, there are some "Precursor m/z Error [Da]" that show up rather frequent, e.g. -61.7Da (54x), -46.5 (1370x), -31 (915x), -23.3 (218x), etc.

so really similar to last time.

**Comment by ulriche** [comment]
found the time to open the project in PS 1.7.0 - and no problem there.

so whatever marc did to fix it got lost with the update to 1.7.1 - I think.

**Comment by hbarsnes** [comment]
Try loading the same data with v1.7.1 a couple more times. As the previous error was due to multiple threads accessing the peptide mass at the same time. Thus when loading the same identical data in PeptideShaker multiple times it sometimes worked and sometimes not. However, after adding the fix I tested loading the same dataset 5-6 times in a row and could not reproduce the issue. (Something that was not the case before the fix.) But I guess there can be another similar issue that we have yet to locate and correct...

**Comment by ulriche** [comment]
strange ... I loaded for sure something like 4-5 different SearchGUI
results already, and always the same problem. I have something running
right now but will try again afterwards. If it happens the next two times
again, I will send you my SearchGUI project plus database and mgf. deal? or
do you prefer the actual PeptideShaker Project? or both?

**Comment by hbarsnes** [comment]
The error happens in the processing, so I would need the SearchGUI output to reproduce the error. However, the zipped PeptideShaker project could also be interesting as it can be used as a quick test. So both. :)

**Comment by hbarsnes** [comment]
The issue should be fixed in PeptideShaker v1.7.2. If not, let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
it is strange ... still hitting this issue once in a while. typically half of the PSMs are off then ...

**Comment by ulriche** [comment]
but think most of the time it is comet (gut feeling but not sure) - will try to keep track of that.

**Comment by ulriche** [comment]
ok - now same issue for comet, msgf+, and MS-amanda. can it be a problem when I run SearchGUI on Computer-A and PeptideShaker on Computer-B? because that's what I am currently doing ...

**Comment by mvaudel** [comment]
Hi Ulrich,

Can it be that the computers have different decimal separators? You can see
this in the windows regional settings. If you make the data available to
us, we should be able to inspect this more in details.

Best regards,

Marc

2016-02-13 23:12 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
interesting point ... will definitely check that.

but chris is keeping me on the tip of my toes today, so most likely won't
manage before later in the evening today.

keep you posted and thanks already!

**Comment by ulriche** [comment]
here a screenshot ...

[image: Inline image 1]

left: my computer where I ran PeptideShaker - set to Canada
right: the server where I run SearchGUI - set to US.

there is a difference in data and time formats

but number formats are the same (besides of metric vs US)
[image: Inline image 2]

but the negative currency format looks different - but can that be the deal
breaker?
[image: Inline image 3]

time is the same again
[image: Inline image 4]


date formats are different (as seen also already above)
[image: Inline image 5]

another difference is the "current language for non-Unicode programs"
[image: Inline image 6]


do you spot the culprit?

**Comment by mvaudel** [comment]
Hi again,

There is nothing wrong as far as I can see. Can there be discrepancies between the search parameters on the different computers?

Do we have these data to try to reproduce the error on our side?

Best regards,

Marc

P.S. Attaching files does not work via email, you need to write your answer on GitHub and attach your files there :)

**Comment by ulriche** [comment]
data are in my dropbox - sent the link earlier ...

something with 29TNnlTYTBGU in it! ;-)

now off for coffee - catch you later.

**Comment by hbarsnes** [comment]
Hi Ulrich,

> data are in my dropbox - sent the link earlier ... something with 29TNnlTYTBGU in it! ;-)

Can you send me the link to these data again? Struggling to find it. :-)

Harald

**Comment by ulrich-eckhard** [comment]
i think it should be these ones ..

https://drive.google.com/folderview?id=0B-gwMljC41WtX29TNnlTYTBGUm8&usp=sharing

**Comment by hbarsnes** [comment]
We've found and fixed a bug that will hopefully correct the problem with the high ppm errors. A beta version is available for testing here: https://www.dropbox.com/s/4g4dcfy43yt9o1x/PeptideShaker-1.10.0-beta.zip?dl=0

Please let us know if this version solves the problem for your data.

**Comment by hbarsnes** [comment]
Hi Ulrich,

PeptideShaker v1.10.0 has now been released which should fix this issue.

Best regards,
Harald
