### ISSUE TITLE
Object not found in cache when saving

### ISSUE THREAD

**Issue by jkgoya** [compomics/peptide-shaker#190]
I ran searchgui to get identification files (comet, ms-amanda, msgf, omssa, and xtandem) as well as mascot, using the same uniprot yeast database with reverse decoys. I'm getting this error after all the files have been loaded. Do you know what the issue is? Is there some limit to the number of files or identifications that peptide-shaker can process in one batch? Thanks for your help.

[PeptideShaker 1.12.2 log.txt](https://github.com/compomics/peptide-shaker/files/373876/PeptideShaker.1.12.2.log.txt)

[20160718_YeastAbundN12.txt](https://github.com/compomics/peptide-shaker/files/373877/20160718_YeastAbundN12.txt)

**Comment by mvaudel** [comment]
Hi,

It rather seems to be a problem with the localization of PTMs. Can you make the SearchGUI output as well as mgf and fasta files available to us? We have encountered this issue before but it is quite difficult to reproduce and debug because it generally happens on large projects. If you can make the data available to us that would definitely help!

In the meantime, when creating your PeptideShaker project, can you try the following: _Edit_ the _Identification Settings_, click on _Show Advanced Settings_, and under _PTM Localization_, set the _Site Alignment of Confident Sites_ to _No_.

Thank you for your help and apologies for the inconvenience,

Marc

**Comment by jkgoya** [comment]
Thanks for the response, I'll try changing that setting.
I replicated the error with a smaller dataset, though it's still pretty big. Here are the files, thanks.

[20160718_YeastAbundN_N12.txt](https://github.com/compomics/peptide-shaker/files/376417/20160718_YeastAbundN_N12.txt)


https://dl.dropboxusercontent.com/u/8465679/uniprot-taxonomy-559292_concatenated_target_decoy.fasta
https://dl.dropboxusercontent.com/u/8465679/mgf_AbundN_N12.tgz
https://dl.dropboxusercontent.com/u/8465679/SearchGuiAbundN_N12.tgz

**Comment by jkgoya** [comment]
I changed the PTM localization setting and the processing proceeded farther than before, but then ran into a different error. I'm guessing this is a separate error? It appears to be due to a retrotransposon having the same protein sequences in many (>50) genomic loci. Should I open a separate issue for this? Thanks for your help!


[20160718_YeastAbundN_N12_no_site_localization.txt](https://github.com/compomics/peptide-shaker/files/376681/20160718_YeastAbundN_N12_no_site_localization.txt)

**Comment by mvaudel** [comment]
Hi again,

Thank you for the extensive testing. There is no need to open a separate issue, fixing one should fix the other :) This error typically occurs on large datasets so indeed processing the files in batches might do the trick. It can be a good temporary solution until I have found a fix.

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi,

PeptideShaker v1.13.0 has just been released which hopefully fixes this issue. If this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by jkgoya** [comment]
Hi,
Thanks for the update! While the first error seems to be resolved, I'm still getting the same error with the very large list of protein accessions I mentioned here: https://github.com/compomics/peptide-shaker/issues/190#issuecomment-234339432


Output log with v.1.13.1:
[2016829_YeastAbundN12.txt](https://github.com/compomics/peptide-shaker/files/454161/2016829_YeastAbundN12.txt)

Thanks!

**Comment by mvaudel** [comment]
Hi again,

Thank you for the update on this one, we will look into it!

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi,

As this issue is the same as #235 we will assume that it is solved for your dataset as well. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
