### ISSUE TITLE
Null pointer when validating matches

### ISSUE THREAD

**Issue by SStoychev01** [compomics/peptide-shaker#245]
Hello,

I'm getting an error (307831) when importing SearchGui data into peptide shaker (the Peptide shaker report is attached).

Regards,

Stoyan

[150217_PepShaker_Report.txt](https://github.com/compomics/peptide-shaker/files/776379/150217_PepShaker_Report.txt)

**Comment by dominik-kopczynski** [comment]
Hi Stoyan,

thank you very much for reporting this issue, the bug was found and fixed. The updated code and program will be available in the next PeptideShaker release.

Cheers,
Dominik

**Comment by SStoychev01** [comment]
Thanks Dominik,

When can we expect the next release? Can we use an older version of Peptide
shaker in the meanwhile?

Regards,

Stoyan

**Comment by hbarsnes** [comment]
Hi Stoyan,

The new release should be online later today. I will let you know when it's out.

Old versions of PeptideShaker are available here: http://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/. I would recommend waiting for the new release though.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Stoyan,

We've just released PeptideShaker v1.16.0 which should fix this problem, if this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by SStoychev01** [comment]
Morning Harald/ Dominik,

Still encountering a problem when importing the data into Peptide Shaker. Seems to be a different issue but no error code shown this time. The report is attached. 

[170217_PepShaker_Report.txt](https://github.com/compomics/peptide-shaker/files/779210/170217_PepShaker_Report.txt)


Regards,

Stoyan

**Comment by mvaudel** [comment]
Hi Stoyan,

Would it be possible to send us the log of the tool? You will find it under the "Help" -> "Bug Report" menu. This problem occurs on large datasets when our back-end database cannot cope with the flow of data. I tried to get rid of it over the past months but somehow it seems it was not a success... If you send me the log I might be able to narrow the issue a bit more. On the long term, @dominik-kopczynski is working on refactoring our back-end completely and you can trust that it is going to be much faster and robust :)

Apologies for the inconvenience,

Marc

**Comment by SStoychev01** [comment]
Sure, bug report attached. Indeed it is a large dataset hat we are trying to import of 60 odds runs.

Thanks for the help.

[160217_PeptideShaker 1.16.0 log.txt](https://github.com/compomics/peptide-shaker/files/779716/160217_PeptideShaker.1.16.0.log.txt)

**Comment by mvaudel** [comment]
Thanks for the log, I will look into it. In the meantime, please verify that the maximal amount of memory available on the machine is given to the tool. You can set this via the _Java Parameters_ menu. If you reduce the number of threads in the processing parameters, that might also avoid the problem :)

Apologies for the inconvenience,

Marc

**Comment by SStoychev01** [comment]
Thanks Marc, after increasing the maximal amount of memory available managed to import the data. One thing to note thou, I could not change the number of threads value. For some reason pressing the "Edit" button does not do anything?

**Comment by hbarsnes** [comment]
Hi Stoyan,

> I could not change the number of threads value. For some reason pressing the "Edit" button does not do anything?

Strange. This should open a new dialog that allows you to set the number of threads/cores. You are trying to do this from the New Project dialog in PeptideShaker right? Could you send us the updated PeptideShaker log file? Perhaps there is something there that can explain why noting happens on your end?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Stoyan,

I figured out the problem with the threads. For some reason we had set a limit at 16 threads/cores. And your default was 32 as far as I can see from your log file.

I will remove the limitation in the next release.

Best regards,
Harald

**Comment by SStoychev01** [comment]
Thanks for the update Harold 




Sent from Samsung tablet


-------- Original message --------
